name: Docker Mifos CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -P $DOCKER_PASSWORD
  
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kalsmic/mifos-web-app:$(date +%s)
      
    - name: Push Image to Docker Hub
      run : docker push kalsmic/mifos-web-app:$(date +%s)
